-- Allows :source $MYVIMRC to work alongisde require(<module>)
local load = function(mod)
	package.loaded[mod] = nil
	return require(mod)
end

load("impatient")
load("plugins")
load("mappings")
load("options")
load("utils")
--> Plugins <--
load("lsp")
load("telescope-setup")
load("cmp-setup")
load("null-ls-setup")
load("treesitter-setup")
load("autopairs-setup")
load("vimwiki-setup")
load("luasnip-setup")
load("nvimtree-setup")
load("lualine-setup")
load("trouble-setup")
-- load("harpoon-setup")
load("quick-scope-setup")
load("friendly-snippets-setup")
load("leap-setup")
load("dressing-setup")
load("cybu-setup")
load("vim-notify-setup")
load("comment-setup")
