-- Allows :source $MYVIMRC to work alongisde require(<module>)
local load = function(mod)
	package.loaded[mod] = nil
	return require(mod)
end

load("impatient")
load("packer-setup")
load("mappings")
load("options")
load("utils")
load("theme")

load("plugins/lsp")
load("plugins/telescope")
load("plugins/cmp")
load("plugins/null-ls")
load("plugins/treesitter")
load("plugins/autopairs")
load("plugins/vimwiki")
load("plugins/luasnip")
load("plugins/nvimtree")
load("plugins/lualine")
load("plugins/trouble")
load("plugins/quick-scope")
load("plugins/friendly-snippets")
load("plugins/comment")
load("plugins/gitsigns")
load("plugins/harpoon")
load("plugins/dressing")
